### ISSUE TITLE
Unable to handle GitHub.Issue.Labels

### ISSUE THREAD

**Issue by yujonglee** [aj-foster/open-api-github#6]
This works:
(Because `open-api-generator` has no label in issue)

```elixir
GitHub.Issues.list_for_repo(
  "aj-foster",
   "open-api-generator"
)
```

But this fails:
(Because `llama_index` has label in issue)

```elixir
GitHub.Issues.list_for_repo(
  "run-llama",
   "llama_index"
)
```

```
** (RuntimeError) TypedDecoder: Unable to decode union type [{GitHub.Issue.Labels, :t}, {:string, :generic}]; not implemented
    (oapi_github 0.3.2) lib/github/plugin/typed_decoder.ex:494: GitHub.Plugin.TypedDecoder.choose_union/2
    (oapi_github 0.3.2) lib/github/plugin/typed_decoder.ex:74: GitHub.Plugin.TypedDecoder.do_decode/2
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (oapi_github 0.3.2) lib/github/plugin/typed_decoder.ex:86: anonymous fn/3 in GitHub.Plugin.TypedDecoder.do_decode/2
    (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (oapi_github 0.3.2) lib/github/plugin/typed_decoder.ex:41: GitHub.Plugin.TypedDecoder.decode_response/2
    (oapi_github 0.3.2) lib/github/client.ex:46: anonymous fn/2 in GitHub.Client.reduce_stack/1
    (elixir 1.16.2) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.2) lib/enum.ex:2582: Enum.reduce_while/3
    (oapi_github 0.3.2) lib/github/client.ex:24: anonymous fn/3 in GitHub.Client.request/1
```

**Comment by aj-foster** [comment]
Hello there 👋🏼 

Thanks for the report! It's hard to keep track of all the unions that need to be decoded; sorry for missing this one. It's unfortunate that GitHub doesn't label all of their objects like Stripe does, so you have to use contextual information like this to know how to decode data.

It's fixed in release `0.3.3`, currently being published! ❤️
